### ISSUE TITLE
Getting error for RMI remote object config

### ISSUE THREAD

**Issue by sathishkumarganesan123** [jmibanez/jmeter-rmi-plugin#25]
![image](https://user-images.githubusercontent.com/26975526/61018607-63a08780-a365-11e9-9275-56c551e65a79.png)

![image](https://user-images.githubusercontent.com/26975526/61018635-7b780b80-a365-11e9-866d-e901e4f9e9b5.png)

please let me know if anything to be done to fix it

**Comment by jmibanez** [comment]
Apologies, I'll update the documentation in the README. 

You'll need to copy all of the relevant dependencies of the plugin (which are in the `lib/production` folder when you run an `ant bootstrap`). If you're using the packaged JAR file in [Releases](https://github.com/jmibanez/jmeter-rmi-plugin/releases), you'll need to at least copy CGLib and Objenesis.

Once you've done that, please let me know if it works for you.

**Comment by jmibanez** [comment]
Just to clarify, you'll need to copy the [CGLib 3.2.5](https://search.maven.org/artifact/cglib/cglib-nodep/3.2.5/jar) and [Objenesis 2.6](https://search.maven.org/artifact/org.objenesis/objenesis/2.6/jar) JARs into the `lib` folder of your JMeter installation. Those JARs are in the `lib/production` folder if you've checked out the project and built locally; otherwise, you can download them from Maven (as linked to in this comment).

**Comment by sathishkumarganesan123** [comment]
Thanks for your quick help. it worked.
